ALTER TABLE coupon_issue
  MODIFY issued_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  MODIFY used_at TIMESTAMP(3) NULL,
  MODIFY canceled_at TIMESTAMP(3) NULL,
  MODIFY expired_at TIMESTAMP(3) NULL;