
spring.application.name=HighFive
spring.profiles.active=dev

# ---- 로그 ----
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n
spring.output.ansi.enabled=ALWAYS

# SQL 파라미터는 OFF
logging.level.org.hibernate.orm.jdbc.bind=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN

# DB 커넥션 풀 상태는 항상 남긴다 (HikariCP 자체 housekeeping 로그 - 성능 모니터링용)
logging.level.com.zaxxer.hikari.pool.HikariPool=DEBUG

spring.task.scheduling.pool.size=8

app.k6.network=highfive-net
app.k6.image=highfive-k6:latest
app.k6.base-url=http://localhost:8080
